name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run typecheck

      - name: Run linting
        run: npm run lint:check

      - name: Run tests
        run: npm run test:ci

      - name: Upload coverage reports
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            package.json
            README.md
            LICENSE

  version-check:
    name: Check Version Bump
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    outputs:
      should-release: ${{ steps.check-version.outputs.should-release }}
      new-version: ${{ steps.check-version.outputs.new-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if version was bumped
        id: check-version
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Get the last tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          LAST_VERSION=${LAST_TAG#v}
          
          echo "Current version: $CURRENT_VERSION"
          echo "Last version: $LAST_VERSION"
          
          if [ "$CURRENT_VERSION" != "$LAST_VERSION" ]; then
            echo "should-release=true" >> $GITHUB_OUTPUT
            echo "new-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            echo "Version bumped from $LAST_VERSION to $CURRENT_VERSION"
          else
            echo "should-release=false" >> $GITHUB_OUTPUT
            echo "No version bump detected"
          fi

  tag-version-check:
    name: Check Tag Version
    runs-on: ubuntu-latest
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/v')
    outputs:
      should-release: ${{ steps.check-tag-version.outputs.should-release }}
      new-version: ${{ steps.check-tag-version.outputs.new-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check tag version
        id: check-tag-version
        run: |
          # Extract version from tag (e.g., v0.1.2 -> 0.1.2)
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          
          # Get version from package.json
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          
          echo "Tag version: $TAG_VERSION"
          echo "Package version: $PACKAGE_VERSION"
          
          if [ "$TAG_VERSION" = "$PACKAGE_VERSION" ]; then
            echo "should-release=true" >> $GITHUB_OUTPUT
            echo "new-version=$TAG_VERSION" >> $GITHUB_OUTPUT
            echo "Tag version matches package version"
          else
            echo "should-release=false" >> $GITHUB_OUTPUT
            echo "Tag version does not match package version"
          fi

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [test, build]
    if: |
      (github.ref == 'refs/heads/main' && github.event_name == 'push') ||
      startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get-version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            # Extract version from tag (e.g., v0.1.2 -> 0.1.2)
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Version from tag: $VERSION"
          else
            # Get version from package.json
            VERSION=$(node -p "require('./package.json').version")
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Version from package.json: $VERSION"
          fi

      - name: Create Git tag (if not exists)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          VERSION=${{ steps.get-version.outputs.version }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          release_name: Release v${{ steps.get-version.outputs.version }}
          body: |
            ## What's Changed
            
            This release includes:
            - Bug fixes and improvements
            - Updated dependencies
            
            ## Installation
            
            ```bash
            npm install mirad-sms-core@${{ steps.get-version.outputs.version }}
            ```
          draft: false
          prerelease: false

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: [test, build, create-release]
    if: |
      (github.ref == 'refs/heads/main' && github.event_name == 'push') ||
      startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level moderate

      - name: Run dependency check
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Check for known vulnerabilities
        run: npx audit-ci --moderate
